param(
    [string]$OutputDir = "target/release-secrets",
    [string]$KeyId,
    [switch]$ListKeys,
    [switch]$GenerateKey
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Get-GpgCommand {
    $cmd = Get-Command gpg -ErrorAction SilentlyContinue
    if ($cmd) {
        return $cmd.Path
    }

    $fallbacks = @(
        "C:\Program Files\GnuPG\bin\gpg.exe",
        "C:\Program Files (x86)\GnuPG\bin\gpg.exe"
    )

    foreach ($path in $fallbacks) {
        if (Test-Path $path) {
            return $path
        }
    }

    throw "gpg was not found on PATH or common install locations."
}

function Resolve-KeyId {
    param([string]$GpgPath)

    $listOutput = & $GpgPath --list-secret-keys --keyid-format LONG
    if (-not $listOutput) {
        throw "No secret keys found. Generate one with: gpg --full-generate-key"
    }

    foreach ($line in $listOutput) {
        if ($line -match "^\s*sec\s+\S+/([A-F0-9]+)\s") {
            return $Matches[1]
        }
    }

    throw "Could not parse a secret key id from gpg output."
}

try {
    $gpg = Get-GpgCommand
    Write-Host "Using gpg: $gpg"

    if ($ListKeys) {
        & $gpg --list-secret-keys --keyid-format LONG
        exit 0
    }

    if ($GenerateKey) {
        Write-Host "Starting interactive key generation..."
        & $gpg --full-generate-key
    }

    $resolvedKeyId = $KeyId
    if (-not $resolvedKeyId) {
        $resolvedKeyId = Resolve-KeyId -GpgPath $gpg
    }

    New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

    $privateKeyFile = Join-Path $OutputDir "gpg-private-key.asc"
    $publicKeyFile = Join-Path $OutputDir "gpg-public-key.asc"
    $keyIdFile = Join-Path $OutputDir "gpg-key-id.txt"
    $secretsTemplateFile = Join-Path $OutputDir "github-secrets-template.txt"
    $nextStepsFile = Join-Path $OutputDir "next-steps.txt"

    $privateKey = (& $gpg --armor --export-secret-keys $resolvedKeyId) -join [Environment]::NewLine
    if (-not $privateKey) {
        throw "Private key export produced no output for key id $resolvedKeyId."
    }
    Set-Content -Path $privateKeyFile -Value $privateKey -Encoding ascii

    $publicKey = (& $gpg --armor --export $resolvedKeyId) -join [Environment]::NewLine
    if (-not $publicKey) {
        throw "Public key export produced no output for key id $resolvedKeyId."
    }
    Set-Content -Path $publicKeyFile -Value $publicKey -Encoding ascii

    Set-Content -Path $keyIdFile -Value $resolvedKeyId -Encoding ascii

    @"
GitHub repository secrets to add:

CENTRAL_TOKEN_USERNAME=<from Sonatype Central user token>
CENTRAL_TOKEN_PASSWORD=<from Sonatype Central user token>
GPG_PASSPHRASE=<your GPG key passphrase>
GPG_PRIVATE_KEY=<paste full contents of gpg-private-key.asc>

Files generated by this script:
- gpg-private-key.asc
- gpg-public-key.asc
- gpg-key-id.txt
"@ | Set-Content -Path $secretsTemplateFile -Encoding ascii

    @"
1. Open GitHub -> Settings -> Secrets and variables -> Actions.
2. Add the four secrets listed in github-secrets-template.txt.
3. Keep gpg-private-key.asc private.
4. (Optional) Publish gpg-public-key.asc to a public keyserver/profile.
5. Trigger .github/workflows/release.yml via tag v<version> or workflow_dispatch.

Useful copy commands:
Get-Content "$privateKeyFile" -Raw | Set-Clipboard
Get-Content "$publicKeyFile" -Raw | Set-Clipboard
"@ | Set-Content -Path $nextStepsFile -Encoding ascii

    Write-Host ""
    Write-Host "Export complete."
    Write-Host "Key ID: $resolvedKeyId"
    Write-Host "Output directory: $OutputDir"
    Write-Host "Private key file: $privateKeyFile"
    Write-Host "Public key file:  $publicKeyFile"
    Write-Host "Template file:    $secretsTemplateFile"
    Write-Host "Next steps file:  $nextStepsFile"
}
catch {
    Write-Error $_.Exception.Message
    exit 1
}
